#!/bin/sh

set -e

if [ $# != 1 ]
then
	echo "usage: $0 version"
	exit 1
fi

FILENAME="herrie-$1.tar.gz"
TARBALL="www/distfiles/$FILENAME"

cd `dirname $0`

if [ -e $TARBALL ]
then
	echo "$TARBALL: file already exists"
	exit 1
fi

mkdir -p www/distfiles
git archive --format=tar --prefix="herrie-$1/" HEAD:herrie |
    gzip -9 > $TARBALL

cd www/distfiles
md5 $FILENAME
sha256 $FILENAME
stat -f "SIZE ($FILENAME) = %z" $FILENAME

echo "don't forget to run ./updatestuff!"
