#!/bin/sh

set -e

# Make sure we are in the proper directory
cd `dirname $0`/herrie/src

# Update depends file
make -C ../../misc cdepcalc
../../misc/cdepcalc

# Update translations
xgettext -k_ *.c
for i in de ga nl pl ru sv tr vi
do
	msgmerge ../lang/$i.po messages.po > tmp.po
	mv tmp.po ../lang/$i.po
done

mv messages.po ../lang/herrie.pot
