#!/bin/sh

set -e

# Make sure we are in the proper directory
cd `dirname $0`

# Update WWW manpage
tbl < herrie/herrie.1 | groff -S -Wall -mtty-char -man -Tascii | col -b > www/herrie.1.txt

cd herrie/src

# Update depends file
fastdep *.c |
    perl -pe 's/^\t//; s/\\\n//; s/\.h//' |
    grep -v '^conftest\.o:' |
    perl -pe 's/^(.*?)\.o: .*?\.c /DEPENDS_$1="/; s/$/"/; s/stdinc ?//' > ../depends

# Update translations
xgettext -k_ *.c
for i in nl tr
do
	msgmerge ../lang/$i.po messages.po > tmp.po
	mv tmp.po ../lang/$i.po
done

mv messages.po ../lang/herrie.pot
