#!/bin/sh

set -e

# Make sure we are in the proper directory
cd `dirname $0`/herrie/src

# Update depends file
make -C ../../misc cdepcalc
../../misc/cdepcalc

# Update translations
xgettext -k_ *.c
mv messages.po ../po/herrie.pot

cd ../po
for i in *.po
do
	msgmerge $i herrie.pot > tmp.po
	mv tmp.po $i
done
