#!/bin/sh

printf 'Content-Type: text/plain\n\r\n'
git --git-dir=/home/ed/.repos/public-git/herrie cat-file blob \
	`git --git-dir=/home/ed/.repos/public-git/herrie ls-tree HEAD herrie/ChangeLog | cut -f 3 -d ' ' | cut -f 1`
